[package]
name = "chip-8-emu"
version = "1.0.0"
authors = ["Hugo Moreda (keelus)]"]
edition = "2021"

[dependencies]
imgui = "0.12.0"
imgui-glow-renderer = "0.12.0"
imgui-sdl2-support = "0.12.0"
lazy_static = "1.5.0"
mint = "0.5.9"
rand = "0.8.5"
rfd = "0.14.1"
sdl2 = "0.34.0"
